#
# Makefile for sensor chip drivers.
#

obj-$(CONFIG_HWMON)		+= hwmon.o
obj-$(CONFIG_HWMON_VID)		+= hwmon-vid.o

# Native drivers
obj-$(CONFIG_SENSORS_AB8500)	+= abx500.o ab8500.o
obj-$(CONFIG_SENSORS_AB5500)	+= abx500.o ab5500.o
obj-$(CONFIG_SENSORS_DBX500)	+= dbx500.o

