#
# Makefile for ST-Ericsson CG2900 connectivity combo controller
#

ccflags-y :=					\
	-Idrivers/staging/cg2900/include

obj-$(CONFIG_BT_CG2900)		+= btcg2900.o
obj-$(CONFIG_CG2900_UART)	+= hci_ldisc.o
