#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_ZINITIX_BT404_U8500)	+= bt404_ts.o
obj-$(CONFIG_TOUCHSCREEN_ZINITIX_U8500)		+= zinitix_touch.o
obj-$(CONFIG_TOUCHSCREEN_ATMEL_MXT224E_U8500)	+= mxt224e.o

