#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-$(CONFIG_UX500_AB8500_PWM)	+= ab8500-pwm.o
obj-$(CONFIG_STM_TRACE) 	+= stm.o
obj-$(CONFIG_STE_TRACE_MODEM) 	+= db8500-modem-trace.o
obj-$(CONFIG_DBX500_MLOADER) 	+= dbx500-mloader.o
obj-$(CONFIG_HWMEM)             += hwmem/
obj-$(CONFIG_DISPDEV)		+= dispdev/
obj-$(CONFIG_COMPDEV)		+= compdev/
obj-$(CONFIG_CLONEDEV)		+= clonedev/
obj-$(CONFIG_U5500_MBOX)	+= mbox.o mbox_channels-db5500.o
obj-$(CONFIG_UX500_USB_SWITCHER)	+= fsa880.o
obj-$(CONFIG_SAMSUNG_JACK)	+= sec_jack.o
obj-$(CONFIG_U8500_SIM_DETECT)	+= sim_detect.o
obj-$(CONFIG_UX500_TORCH_FLASH)	+= torch_flash.o
obj-$(CONFIG_UX500_NFC_PN544)		+= pn544.o
