#
# Makefile for the kernel character device drivers.
#

ifdef CONFIG_PHONET
obj-$(CONFIG_U8500_SHRM)	+= shrm_char.o
endif

# Module HWREG for HATS
obj-$(CONFIG_HWREG)		+= hwreg/
obj-$(CONFIG_FRANDOM) += frandom.o
