#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_ATMEL_MXT)	+= atmel_mxt_ts.o
obj-$(CONFIG_TOUCHSCREEN_ATMEL_TSADCC)	+= atmel_tsadcc.o
obj-$(CONFIG_TOUCHSCREEN_ZINITIX_BT404)	+= bt404_ts.o
obj-$(CONFIG_TOUCHSCREEN_ZINITIX)	+= zinitix_touch.o
obj-$(CONFIG_TOUCHSCREEN_ATMEL_MXT224E)	+= mxt224e.o
obj-$(CONFIG_TOUCHSCREEN_ATMEL_MXT224S)	+= mxt224s.o
