# Makefile for staging directory

obj-$(CONFIG_CG2900)		+= cg2900/
#obj-$(CONFIG_CW1200)   		+= cw1200/
obj-$(CONFIG_ANDROID)		+= android/
obj-$(CONFIG_U8500_MMIO)	+= mmio/
obj-$(CONFIG_U8500_FLASH)	+= camera_flash/
obj-$(CONFIG_U8500_CM)		+= nmf-cm/
