#!/stage1/busybox sh
_PATH="$PATH"
export PATH=/stage1

busybox cd /
busybox date >>boot.txt
exec >>boot.txt 2>&1
busybox rm init
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

busybox mount -t ext4 /dev/block/mmcblk0p17 /ramdisk

if ! busybox grep -q bootmode=2 /proc/cmdline ; then

	for i in /ramdisk/modules/autoload/*.ko
	do
		busybox insmod $i
	done
	
	if busybox test -f /ramdisk/00userinit ; then
		busybox sh /ramdisk/00userinit
	fi
fi

busybox chmod 644 /ramdisk/boot.cpio

load_image=/ramdisk/boot.cpio
lvm=/ramdisk/lvm.cpio

if busybox grep -q bootmode=2 /proc/cmdline ; then
	# recovery boot
	busybox chmod 644 /ramdisk/recovery.cpio
	load_image=/ramdisk/recovery.cpio
	# since it's pain, load j4fs and param from separate partition
	busybox insmod /ramdisk/modules/j4fs.ko
	busybox insmod /ramdisk/modules/param.ko
	if ! busybox test -f /mnt ; then
		busybox mkdir /mnt
		if ! busybox test -f /mnt/.lfs ; then
			busybox mkdir /mnt/.lfs
		fi
	fi

	busybox mount -t j4fs /dev/block/mmcblk0p1 /mnt/.lfs
	
	if busybox test -f /ramdisk/00recovery ; then
		busybox sh /ramdisk/00recovery
	fi
fi

if busybox test -f ${load_image} ; then
	busybox cpio -i < ${load_image}
fi

if busybox test -f ${load_image}.gz ; then
	busybox zcat ${load_image}.gz | busybox cpio -i -u
fi

if busybox test -f ${lvm} ; then
	busybox cpio -i < ${lwm}
fi

if busybox test -f ${lvm}.gz ; then
	busybox zcat ${lvm}.gz | busybox cpio -i -u
fi

busybox umount /sys
busybox umount /proc
busybox date >>boot.txt
busybox rm -fr /stage1 /dev/*
export PATH="${_PATH}"
exec /init
