#!/stage1/busybox sh
_PATH="$PATH"
export PATH=/stage1

busybox mount -t ext4 /dev/block/mmcblk0p17 /ramdisk
busybox rm /ramdisk/last_boot.txt 
busybox date >>/ramdisk/last_boot.txt
exec >>/ramdisk/last_boot.txt 2>&1

busybox cd /
busybox rm init
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

load_image=/ramdisk/boot.cpio
lvm=/ramdisk/lvm.cpio

busybox insmod /ramdisk/modules/startup_reason.ko
busybox insmod /ramdisk/modules/exfat.ko
busybox insmod /ramdisk/modules/f2fs.ko

if ! busybox grep -q bootmode=2 /proc/cmdline ; then

	for i in /ramdisk/modules/autoload/*.ko
	do
		busybox insmod $i
	done

	busybox sh /ramdisk/00userinit
fi

if busybox grep -q lcdtype=4 /proc/cmdline ; then
	busybox insmod /ramdisk/modules/display-ws2401_dpi.ko
fi

if ! busybox grep -q lcdtype=4 /proc/cmdline ; then
	busybox insmod /ramdisk/modules/display-s6d27a1_dpi.ko
fi

if busybox grep -q lcdtype=13 /proc/cmdline ; then
	busybox insmod /ramdisk/modules/display-s6d27a1_dpi.ko
fi

if busybox grep -q bootmode=2 /proc/cmdline ; then
	# recovery boot
	busybox chmod 644 /ramdisk/recovery.cpio
	load_image=/ramdisk/recovery.cpio
	# since it's pain, load j4fs and param from separate partition
	busybox insmod /ramdisk/modules/j4fs.ko
	busybox insmod /ramdisk/modules/param.ko

	busybox mount -t j4fs /dev/block/mmcblk0p1 /mnt/.lfs
	busybox sh /ramdisk/00recovery
fi

if test -f ${load_image} ; then
	busybox cpio -i < ${load_image}
fi

if test -f ${load_image}.gz ; then
	busybox zcat ${load_image}.gz | busybox cpio -i -u
fi

if test -f ${lvm} ; then
	busybox cpio -i < ${lwm}
fi

if test -f ${lvm}.gz ; then
	busybox zcat ${lvm}.gz | cpio -i -u
fi

busybox umount /sys
busybox umount /proc
busybox date >>/ramdisk/last_boot.txt
busybox rm -fr /stage1 /dev/*
export PATH="${_PATH}"
exec /init
