#
# Makefile for AB8500 device drivers
#
obj-$(CONFIG_STE_AUDIO_IO_DEV)	+= ste_audio_io.o
ste_audio_io-objs := ste_audio_io_dev.o\
			ste_audio_io_core.o\
			ste_audio_io_func.o\
			ste_audio_io_hwctrl_common.o

