#
# Makefile for drivers/telephony
#

obj-$(CONFIG_PHONE) += phonedev.o
obj-$(CONFIG_PHONE_IXJ) += ixj.o
obj-$(CONFIG_PHONE_IXJ_PCMCIA) += ixj_pcmcia.o

include $(srctree)/scripts/Makefile_build.thumb2
