#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_KEYBOARD_GPIO_U8500)		+= gpio_keys.o
obj-$(CONFIG_KEYBOARD_CYPRESS_TOUCH_U8500)	+= cypress/
