obj-$(CONFIG_TEE_SUPPORT)		+= tee/
obj-$(CONFIG_MODEM)			+= modem/

obj-y					+= samsung/
obj-$(CONFIG_SAMSUNG_PHONE_SVNET)	+= phone_svn/

obj-$(CONFIG_BATTERY_SAMSUNG)		+= battery/

obj-$(CONFIG_BCM4330)			+= bcmdhd/
obj-$(CONFIG_BCM4334)			+= bcmdhd/
