#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_UX500_KEYBOARD_GPIO)		+= gpio_keys.o
obj-$(CONFIG_UX500_KEYBOARD_GPIO_POLLED)	+= gpio_keys_polled.o
