#
# Makefile for the input misc drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_INPUT_AB8500_ACCDET_U8500)	+= abx500-accdet.o ab8500-accdet.o
obj-$(CONFIG_INPUT_AB8500_PONKEY_U8500)	+= ab8500-ponkey.o
